services:
  restapirabbitmqdemoapp:
    image: artemkoloskov/restapirabbitmqdemoapp
    environment:
      - "RabbitMq/Host=rabbit"
      - "RabbitMq/UserName=guest"
      - "RabbitMq/Password=guest"
    restart: 
      always
    depends_on:
      - rabbit
    networks:
      - localnet

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - localnet

networks:
  localnet:
    external:
      name: localnet